### ISSUE TITLE
Error en npm start

### ISSUE THREAD

**Issue by DiegoECQ** [miguelghz/Intro-ReactJS#2]
Hola Estimado, tengo el siguiente error:

![image](https://cloud.githubusercontent.com/assets/19826929/26449907/e3814144-4122-11e7-9402-91f52cf03d3e.png)

**Comment by juanicotolengo** [comment]
Tuve el mismo problema, y es que _npm_ no lograba instalar la dependencia _react-scripts_ .
Podés instalar el paquete globalmente:

`npm install -g react-scripts
`
Y luego debería funcionar.
